---
name: changelog and linters

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main
  linters:
    uses: tremble/ansible_github_actions/.github/workflows/tox.yml@tox/labels
    with:
      envname: ""
      labelname: "lint"
      runname: "Run code linters"
