---
name: update collection variables

concurrency:
  group: ${{ github.workflow }} @ ${{ github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - stable-*
  pull_request_target:
jobs:
  update-variables:
    uses: ansible-network/github_actions/.github/workflows/update_aws_variables.yml@4678c7401d0247aee67c880ddf21bf6fcf1aacc3 # @main as of 2026-07-31
